; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+v -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32IV %s

declare i32 @llvm.riscv.vsetvl(i32, i32) #1

define i32 @test_vsetvl__e8m1(i32 %rvl)  {
entry:
; RV32IV: vsetvl a1, a0, a1 
  %0 = tail call i32 @llvm.riscv.vsetvl(i32 %rvl, i32 9) #2
  ret i32 %0
}
