; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+f,+experimental-zfh -target-abi=ilp32f < %s | FileCheck %s

define half @test_ret(half* %p) nounwind {
; CHECK-LABEL: test_ret:
; CHECK:       # %bb.0:
; CHECK-NEXT:    flh	fa0, 0(a0)
; CHECK-NEXT:    ret
  %a = load half, half* %p
  ret half %a
}