; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr +experimental-zfh < %s | FileCheck %s

define void @test_load_store(half* %p, half* %q) nounwind {
; CHECK-LABEL: test_load_store:
; CHECK:       # %bb.0:
; CHECK-NEXT:    flh	ft0, 0(a0)
; CHECK-NEXT:    fsh	ft0, 0(a1)
; CHECK-NEXT:    ret
  %a = load half, half* %p
  store half %a, half* %q
  ret void 
}