; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

define i32 @add8(i32 %a, i32 %b) {
; CHECK-LABEL: add8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    add8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.add8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.add8.i32(i32, i32)

define i32 @add16(i32 %a, i32 %b) {
; CHECK-LABEL: add16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    add16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.add16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.add16.i32(i32, i32)

define i32 @ave(i32 %a, i32 %b) {
; CHECK-LABEL: ave:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ave a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ave.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ave.i32(i32, i32)

define i32 @bitrev(i32 %a, i32 %b) {
; CHECK-LABEL: bitrev:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bitrev a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.bitrev.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @bitrevi(i32 %a, i32 %b) {
; CHECK-LABEL: bitrevi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bitrevi a0, a0, 1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.bitrev.i32(i32 %a, i32 1)
  ret i32 %0
}

declare i32 @llvm.riscv.bitrev.i32(i32, i32)

define i32 @bpick(i32 %a, i32 %b, i32 %c) {
; CHECK-LABEL: bpick:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bpick a0, a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.bpick.i32(i32 %a, i32 %b, i32 %c)
  ret i32 %0
}

declare i32 @llvm.riscv.bpick.i32(i32, i32, i32)

define i32 @clrs8(i32 %a) {
; CHECK-LABEL: clrs8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    clrs8 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.clrs8.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.clrs8.i32(i32)

define i32 @clrs16(i32 %a) {
; CHECK-LABEL: clrs16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    clrs16 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.clrs16.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.clrs16.i32(i32)

define i32 @clrs32(i32 %a) {
; CHECK-LABEL: clrs32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    clrs32 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.clrs32.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.clrs32.i32(i32)

define i32 @clz8(i32 %a) {
; CHECK-LABEL: clz8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    clz8 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.clz8.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.clz8.i32(i32)

define i32 @clz16(i32 %a) {
; CHECK-LABEL: clz16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    clz16 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.clz16.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.clz16.i32(i32)

define i32 @clz32(i32 %a) {
; CHECK-LABEL: clz32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    clz32 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.clz32.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.clz32.i32(i32)

define i32 @cmpeq8(i32 %a, i32 %b) {
; CHECK-LABEL: cmpeq8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cmpeq8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.cmpeq8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.cmpeq8.i32(i32, i32)

define i32 @cmpeq16(i32 %a, i32 %b) {
; CHECK-LABEL: cmpeq16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cmpeq16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.cmpeq16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.cmpeq16.i32(i32, i32)

define i32 @cras16(i32 %a, i32 %b) {
; CHECK-LABEL: cras16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cras16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.cras16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.cras16.i32(i32, i32)

define i32 @crsa16(i32 %a, i32 %b) {
; CHECK-LABEL: crsa16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    crsa16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.crsa16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.crsa16.i32(i32, i32)

define i32 @insb(i32 %a, i32 %b) {
; CHECK-LABEL: insb:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    insb a0, a1, 3
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.insb.i32(i32 %a, i32 %b, i32 3)
  ret i32 %0
}

declare i32 @llvm.riscv.insb.i32(i32, i32, i32)

define i32 @kabs8(i32 %a) {
; CHECK-LABEL: kabs8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kabs8 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kabs8.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.kabs8.i32(i32)

define i32 @kabs16(i32 %a) {
; CHECK-LABEL: kabs16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kabs16 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kabs16.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.kabs16.i32(i32)

define i32 @kabsw(i32 %a) {
; CHECK-LABEL: kabsw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kabsw a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kabsw.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.kabsw.i32(i32)

define i32 @kadd8(i32 %a, i32 %b) {
; CHECK-LABEL: kadd8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kadd8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kadd8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kadd8.i32(i32, i32)

define i32 @kadd16(i32 %a, i32 %b) {
; CHECK-LABEL: kadd16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kadd16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kadd16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kadd16.i32(i32, i32)

define i32 @kaddh(i32 %a, i32 %b) {
; CHECK-LABEL: kaddh:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kaddh a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kaddh.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kaddh.i32(i32, i32)

define i32 @kaddw(i32 %a, i32 %b) {
; CHECK-LABEL: kaddw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kaddw a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kaddw.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kaddw.i32(i32, i32)

define i32 @kcras16(i32 %a, i32 %b) {
; CHECK-LABEL: kcras16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kcras16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kcras16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kcras16.i32(i32, i32)

define i32 @kcrsa16(i32 %a, i32 %b) {
; CHECK-LABEL: kcrsa16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kcrsa16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kcrsa16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kcrsa16.i32(i32, i32)

define i32 @kdmbb(i32 %a, i32 %b) {
; CHECK-LABEL: kdmbb:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kdmbb a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kdmbb.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kdmbb.i32.i32(i32, i32)

define i32 @kdmbt(i32 %a, i32 %b) {
; CHECK-LABEL: kdmbt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kdmbt a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kdmbt.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kdmbt.i32.i32(i32, i32)

define i32 @kdmtt(i32 %a, i32 %b) {
; CHECK-LABEL: kdmtt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kdmtt a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kdmtt.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kdmtt.i32.i32(i32, i32)

define i32 @kdmabb(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kdmabb:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kdmabb a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kdmabb.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kdmabb.i32.i32(i32, i32, i32)

define i32 @kdmabt(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kdmabt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kdmabt a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kdmabt.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kdmabt.i32.i32(i32, i32, i32)

define i32 @kdmatt(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kdmatt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kdmatt a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kdmatt.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kdmatt.i32.i32(i32, i32, i32)

define i32 @khm8(i32 %a, i32 %b) {
; CHECK-LABEL: khm8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    khm8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.khm8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.khm8.i32(i32, i32)

define i32 @khmx8(i32 %a, i32 %b) {
; CHECK-LABEL: khmx8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    khmx8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.khmx8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.khmx8.i32(i32, i32)

define i32 @khm16(i32 %a, i32 %b) {
; CHECK-LABEL: khm16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    khm16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.khm16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.khm16.i32(i32, i32)

define i32 @khmx16(i32 %a, i32 %b) {
; CHECK-LABEL: khmx16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    khmx16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.khmx16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.khmx16.i32(i32, i32)

define i32 @khmbb(i32 %a, i32 %b) {
; CHECK-LABEL: khmbb:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    khmbb a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.khmbb.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.khmbb.i32.i32(i32, i32)

define i32 @khmbt(i32 %a, i32 %b) {
; CHECK-LABEL: khmbt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    khmbt a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.khmbt.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.khmbt.i32.i32(i32, i32)

define i32 @khmtt(i32 %a, i32 %b) {
; CHECK-LABEL: khmtt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    khmtt a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.khmtt.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.khmtt.i32.i32(i32, i32)

define i32 @kmabb(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmabb:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmabb a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmabb.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmabb.i32.i32(i32, i32, i32)

define i32 @kmabt(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmabt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmabt a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmabt.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmabt.i32.i32(i32, i32, i32)

define i32 @kmatt(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmatt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmatt a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmatt.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmatt.i32.i32(i32, i32, i32)

define i32 @kmada(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmada:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmada a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmada.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmada.i32.i32(i32, i32, i32)

define i32 @kmaxda(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmaxda:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmaxda a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmaxda.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmaxda.i32.i32(i32, i32, i32)

define i32 @kmads(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmads:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmads a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmads.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmads.i32.i32(i32, i32, i32)

define i32 @kmadrs(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmadrs:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmadrs a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmadrs.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmadrs.i32.i32(i32, i32, i32)

define i32 @kmaxds(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmaxds:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmaxds a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmaxds.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmaxds.i32.i32(i32, i32, i32)

define i32 @kmda(i32 %a, i32 %b) {
; CHECK-LABEL: kmda:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmda a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmda.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmda.i32.i32(i32, i32)

define i32 @kmxda(i32 %a, i32 %b) {
; CHECK-LABEL: kmxda:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmxda a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmxda.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmxda.i32.i32(i32, i32)

define i32 @kmmac(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmmac:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmac a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmac.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmac.i32(i32, i32, i32)

define i32 @kmmac_u(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmmac_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmac.u a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmac.u.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmac.u.i32(i32, i32, i32)

define i32 @kmmawb(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmmawb:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmawb a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmawb.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmawb.i32.i32(i32, i32, i32)

define i32 @kmmawb_u(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmmawb_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmawb.u a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmawb.u.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmawb.u.i32.i32(i32, i32, i32)

define i32 @kmmawb2(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmmawb2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmawb2 a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmawb2.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmawb2.i32.i32(i32, i32, i32)

define i32 @kmmawb2_u(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmmawb2_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmawb2.u a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmawb2.u.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmawb2.u.i32.i32(i32, i32, i32)

define i32 @kmmawt(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmmawt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmawt a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmawt.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmawt.i32.i32(i32, i32, i32)

define i32 @kmmawt_u(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmmawt_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmawt.u a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmawt.u.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmawt.u.i32.i32(i32, i32, i32)

define i32 @kmmawt2(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmmawt2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmawt2 a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmawt2.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmawt2.i32.i32(i32, i32, i32)

define i32 @kmmawt2_u(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmmawt2_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmawt2.u a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmawt2.u.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmawt2.u.i32.i32(i32, i32, i32)

define i32 @kmmsb(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmmsb:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmsb a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmsb.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmsb.i32(i32, i32, i32)

define i32 @kmmsb_u(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmmsb_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmsb.u a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmsb.u.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmsb.u.i32(i32, i32, i32)

define i32 @kmmwb2(i32 %a, i32 %b) {
; CHECK-LABEL: kmmwb2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmwb2 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmwb2.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmwb2.i32.i32(i32, i32)

define i32 @kmmwb2_u(i32 %a, i32 %b) {
; CHECK-LABEL: kmmwb2_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmwb2.u a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmwb2.u.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmwb2.u.i32.i32(i32, i32)

define i32 @kmmwt2(i32 %a, i32 %b) {
; CHECK-LABEL: kmmwt2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmwt2 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmwt2.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmwt2.i32.i32(i32, i32)

define i32 @kmmwt2_u(i32 %a, i32 %b) {
; CHECK-LABEL: kmmwt2_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmmwt2.u a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmmwt2.u.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmmwt2.u.i32.i32(i32, i32)

define i32 @kmsda(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmsda:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmsda a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmsda.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmsda.i32.i32(i32, i32, i32)

define i32 @kmsxda(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: kmsxda:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmsxda a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kmsxda.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kmsxda.i32.i32(i32, i32, i32)

define i32 @ksllw(i32 %a, i32 %b) {
; CHECK-LABEL: ksllw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ksllw a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ksllw.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @kslliw(i32 %a, i32 %b) {
; CHECK-LABEL: kslliw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kslliw a0, a0, 20
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ksllw.i32(i32 %a, i32 20)
  ret i32 %0
}

declare i32 @llvm.riscv.ksllw.i32(i32, i32)

define i32 @ksll8(i32 %a, i32 %b) {
; CHECK-LABEL: ksll8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ksll8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ksll8.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @kslli8(i32 %a, i32 %b) {
; CHECK-LABEL: kslli8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kslli8 a0, a0, 3
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ksll8.i32.i32(i32 %a, i32 3)
  ret i32 %0
}

declare i32 @llvm.riscv.ksll8.i32.i32(i32, i32)

define i32 @ksll16(i32 %a, i32 %b) {
; CHECK-LABEL: ksll16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ksll16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ksll16.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @kslli16(i32 %a, i32 %b) {
; CHECK-LABEL: kslli16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kslli16 a0, a0, 11
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ksll16.i32.i32(i32 %a, i32 11)
  ret i32 %0
}

declare i32 @llvm.riscv.ksll16.i32.i32(i32, i32)

define i32 @kslra8(i32 %a, i32 %b) {
; CHECK-LABEL: kslra8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kslra8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kslra8.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kslra8.i32.i32(i32, i32)

define i32 @kslra8_u(i32 %a, i32 %b) {
; CHECK-LABEL: kslra8_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kslra8.u a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kslra8.u.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kslra8.u.i32.i32(i32, i32)

define i32 @kslra16(i32 %a, i32 %b) {
; CHECK-LABEL: kslra16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kslra16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kslra16.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kslra16.i32.i32(i32, i32)

define i32 @kslra16_u(i32 %a, i32 %b) {
; CHECK-LABEL: kslra16_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kslra16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kslra16.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @kslraw(i32 %a, i32 %b) {
; CHECK-LABEL: kslraw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kslraw a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kslraw.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kslraw.i32(i32, i32)

define i32 @kslraw_u(i32 %a, i32 %b) {
; CHECK-LABEL: kslraw_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kslraw.u a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kslraw.u.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kslraw.u.i32(i32, i32)

define i32 @kstas16(i32 %a, i32 %b) {
; CHECK-LABEL: kstas16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kstas16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kstas16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kstas16.i32(i32, i32)

define i32 @kstsa16(i32 %a, i32 %b) {
; CHECK-LABEL: kstsa16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kstsa16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kstsa16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kstsa16.i32(i32, i32)

define i32 @ksub8(i32 %a, i32 %b) {
; CHECK-LABEL: ksub8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ksub8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ksub8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ksub8.i32(i32, i32)

define i32 @ksub16(i32 %a, i32 %b) {
; CHECK-LABEL: ksub16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ksub16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ksub16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ksub16.i32(i32, i32)

define i32 @ksubh(i32 %a, i32 %b) {
; CHECK-LABEL: ksubh:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ksubh a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ksubh.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ksubh.i32(i32, i32)

define i32 @ksubw(i32 %a, i32 %b) {
; CHECK-LABEL: ksubw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ksubw a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ksubw.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ksubw.i32(i32, i32)

define i32 @kwmmul(i32 %a, i32 %b) {
; CHECK-LABEL: kwmmul:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kwmmul a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kwmmul.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kwmmul.i32(i32, i32)

define i32 @kwmmul_u(i32 %a, i32 %b) {
; CHECK-LABEL: kwmmul_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kwmmul.u a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.kwmmul.u.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.kwmmul.u.i32(i32, i32)

define i32 @maxw(i32 %a, i32 %b) {
; CHECK-LABEL: maxw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    maxw a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.maxw.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.maxw.i32(i32, i32)

define i32 @minw(i32 %a, i32 %b) {
; CHECK-LABEL: minw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    minw a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.minw.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.minw.i32(i32, i32)

define i32 @pbsad(i32 %a, i32 %b) {
; CHECK-LABEL: pbsad:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pbsad a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.pbsad.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.pbsad.i32.i32(i32, i32)

define i32 @pbsada(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: pbsada:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pbsada a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.pbsada.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.pbsada.i32.i32(i32, i32, i32)

define i32 @pkbb16(i32 %a, i32 %b) {
; CHECK-LABEL: pkbb16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pkbb16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.pkbb16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.pkbb16.i32(i32, i32)

define i32 @pkbt16(i32 %a, i32 %b) {
; CHECK-LABEL: pkbt16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pkbt16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.pkbt16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.pkbt16.i32(i32, i32)

define i32 @pktt16(i32 %a, i32 %b) {
; CHECK-LABEL: pktt16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pktt16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.pktt16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.pktt16.i32(i32, i32)

define i32 @pktb16(i32 %a, i32 %b) {
; CHECK-LABEL: pktb16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pktb16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.pktb16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.pktb16.i32(i32, i32)

define i32 @radd8(i32 %a, i32 %b) {
; CHECK-LABEL: radd8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    radd8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.radd8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.radd8.i32(i32, i32)

define i32 @radd16(i32 %a, i32 %b) {
; CHECK-LABEL: radd16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    radd16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.radd16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.radd16.i32(i32, i32)

define i32 @raddw(i32 %a, i32 %b) {
; CHECK-LABEL: raddw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    raddw a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.raddw.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.raddw.i32(i32, i32)

define i32 @rcras16(i32 %a, i32 %b) {
; CHECK-LABEL: rcras16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rcras16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.rcras16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.rcras16.i32(i32, i32)

define i32 @rcrsa16(i32 %a, i32 %b) {
; CHECK-LABEL: rcrsa16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rcrsa16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.rcrsa16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.rcrsa16.i32(i32, i32)

define i32 @rstas16(i32 %a, i32 %b) {
; CHECK-LABEL: rstas16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rstas16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.rstas16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.rstas16.i32(i32, i32)

define i32 @rstsa16(i32 %a, i32 %b) {
; CHECK-LABEL: rstsa16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rstsa16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.rstsa16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.rstsa16.i32(i32, i32)

define i32 @rsub8(i32 %a, i32 %b) {
; CHECK-LABEL: rsub8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rsub8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.rsub8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.rsub8.i32(i32, i32)

define i32 @rsub16(i32 %a, i32 %b) {
; CHECK-LABEL: rsub16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rsub16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.rsub16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.rsub16.i32(i32, i32)

define i32 @rsubw(i32 %a, i32 %b) {
; CHECK-LABEL: rsubw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rsubw a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.rsubw.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.rsubw.i32(i32, i32)

define i32 @sclip8(i32 %a) {
; CHECK-LABEL: sclip8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sclip8 a0, a0, 5
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sclip8.i32.i32(i32 %a, i32 5)
  ret i32 %0
}

declare i32 @llvm.riscv.sclip8.i32.i32(i32, i32)

define i32 @sclip16(i32 %a) {
; CHECK-LABEL: sclip16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sclip16 a0, a0, 6
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sclip16.i32.i32(i32 %a, i32 6)
  ret i32 %0
}

declare i32 @llvm.riscv.sclip16.i32.i32(i32, i32)

define i32 @sclip32(i32 %a) {
; CHECK-LABEL: sclip32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sclip32 a0, a0, 7
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sclip32.i32.i32(i32 %a, i32 7)
  ret i32 %0
}

declare i32 @llvm.riscv.sclip32.i32.i32(i32, i32)

define i32 @scmple8(i32 %a, i32 %b) {
; CHECK-LABEL: scmple8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    scmple8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.scmple8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.scmple8.i32(i32, i32)

define i32 @scmple16(i32 %a, i32 %b) {
; CHECK-LABEL: scmple16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    scmple16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.scmple16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.scmple16.i32(i32, i32)

define i32 @scmplt8(i32 %a, i32 %b) {
; CHECK-LABEL: scmplt8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    scmplt8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.scmplt8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.scmplt8.i32(i32, i32)

define i32 @scmplt16(i32 %a, i32 %b) {
; CHECK-LABEL: scmplt16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    scmplt16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.scmplt16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.scmplt16.i32(i32, i32)

define i32 @sll8(i32 %a, i32 %b) {
; CHECK-LABEL: sll8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sll8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sll8.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @slli8(i32 %a, i32 %b) {
; CHECK-LABEL: slli8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    slli8 a0, a0, 1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sll8.i32.i32(i32 %a, i32 1)
  ret i32 %0
}

declare i32 @llvm.riscv.sll8.i32.i32(i32, i32)

define i32 @sll16(i32 %a, i32 %b) {
; CHECK-LABEL: sll16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sll16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sll16.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @slli16(i32 %a, i32 %b) {
; CHECK-LABEL: slli16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    slli16 a0, a0, 1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sll16.i32.i32(i32 %a, i32 1)
  ret i32 %0
}

declare i32 @llvm.riscv.sll16.i32.i32(i32, i32)

define i32 @smaqa(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: smaqa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smaqa a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smaqa.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smaqa.i32.i32(i32, i32, i32)

define i32 @smaqa_su(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: smaqa_su:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smaqa.su a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smaqa.su.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smaqa.su.i32.i32(i32, i32, i32)

define i32 @smax8(i32 %a, i32 %b) {
; CHECK-LABEL: smax8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smax8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smax8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smax8.i32(i32, i32)

define i32 @smax16(i32 %a, i32 %b) {
; CHECK-LABEL: smax16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smax16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smax16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smax16.i32(i32, i32)

define i32 @smbb16(i32 %a, i32 %b) {
; CHECK-LABEL: smbb16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smbb16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smbb16.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smbb16.i32.i32(i32, i32)

define i32 @smbt16(i32 %a, i32 %b) {
; CHECK-LABEL: smbt16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smbt16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smbt16.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smbt16.i32.i32(i32, i32)

define i32 @smtt16(i32 %a, i32 %b) {
; CHECK-LABEL: smtt16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smtt16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smtt16.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smtt16.i32.i32(i32, i32)

define i32 @smds(i32 %a, i32 %b) {
; CHECK-LABEL: smds:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smds a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smds.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smds.i32.i32(i32, i32)

define i32 @smdrs(i32 %a, i32 %b) {
; CHECK-LABEL: smdrs:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smdrs a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smdrs.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smdrs.i32.i32(i32, i32)

define i32 @smxds(i32 %a, i32 %b) {
; CHECK-LABEL: smxds:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smxds a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smxds.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smxds.i32.i32(i32, i32)

define i32 @smin8(i32 %a, i32 %b) {
; CHECK-LABEL: smin8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smin8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smin8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smin8.i32(i32, i32)

define i32 @smin16(i32 %a, i32 %b) {
; CHECK-LABEL: smin16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smin16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smin16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smin16.i32(i32, i32)

define i32 @smmul(i32 %a, i32 %b) {
; CHECK-LABEL: smmul:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smmul a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smmul.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smmul.i32(i32, i32)

define i32 @smmul_u(i32 %a, i32 %b) {
; CHECK-LABEL: smmul_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smmul.u a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smmul.u.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smmul.u.i32(i32, i32)

define i32 @smmwb(i32 %a, i32 %b) {
; CHECK-LABEL: smmwb:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smmwb a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smmwb.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smmwb.i32.i32(i32, i32)

define i32 @smmwb_u(i32 %a, i32 %b) {
; CHECK-LABEL: smmwb_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smmwb.u a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smmwb.u.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smmwb.u.i32.i32(i32, i32)

define i32 @smmwt(i32 %a, i32 %b) {
; CHECK-LABEL: smmwt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smmwt a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smmwt.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smmwt.i32.i32(i32, i32)

define i32 @smmwt_u(i32 %a, i32 %b) {
; CHECK-LABEL: smmwt_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smmwt.u a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.smmwt.u.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.smmwt.u.i32.i32(i32, i32)

define i32 @sra_u(i32 %a, i32 %b) {
; CHECK-LABEL: sra_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sra.u a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sra.u.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @srai_u(i32 %a, i32 %b) {
; CHECK-LABEL: srai_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srai.u a0, a0, 1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sra.u.i32.i32(i32 %a, i32 1)
  ret i32 %0
}

declare i32 @llvm.riscv.sra.u.i32.i32(i32, i32)

define i32 @sra8(i32 %a, i32 %b) {
; CHECK-LABEL: sra8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sra8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sra8.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @srai8(i32 %a, i32 %b) {
; CHECK-LABEL: srai8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srai8 a0, a0, 1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sra8.i32.i32(i32 %a, i32 1)
  ret i32 %0
}

declare i32 @llvm.riscv.sra8.i32.i32(i32, i32)

define i32 @sra8_u(i32 %a, i32 %b) {
; CHECK-LABEL: sra8_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sra8.u a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sra8.u.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @srai8_u(i32 %a, i32 %b) {
; CHECK-LABEL: srai8_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srai8.u a0, a0, 1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sra8.u.i32.i32(i32 %a, i32 1)
  ret i32 %0
}

declare i32 @llvm.riscv.sra8.u.i32.i32(i32, i32)

define i32 @sra16(i32 %a, i32 %b) {
; CHECK-LABEL: sra16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sra16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sra16.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @srai16(i32 %a, i32 %b) {
; CHECK-LABEL: srai16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srai16 a0, a0, 1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sra16.i32.i32(i32 %a, i32 1)
  ret i32 %0
}

declare i32 @llvm.riscv.sra16.i32.i32(i32, i32)

define i32 @sra16_u(i32 %a, i32 %b) {
; CHECK-LABEL: sra16_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sra16.u a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sra16.u.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @srai16_u(i32 %a, i32 %b) {
; CHECK-LABEL: srai16_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srai16.u a0, a0, 1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sra16.u.i32.i32(i32 %a, i32 1)
  ret i32 %0
}

declare i32 @llvm.riscv.sra16.u.i32.i32(i32, i32)

define i32 @srl8(i32 %a, i32 %b) {
; CHECK-LABEL: srl8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srl8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.srl8.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @srli8(i32 %a, i32 %b) {
; CHECK-LABEL: srli8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srli8 a0, a0, 1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.srl8.i32.i32(i32 %a, i32 1)
  ret i32 %0
}

declare i32 @llvm.riscv.srl8.i32.i32(i32, i32)

define i32 @srl8_u(i32 %a, i32 %b) {
; CHECK-LABEL: srl8_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srl8.u a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.srl8.u.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @srli8_u(i32 %a, i32 %b) {
; CHECK-LABEL: srli8_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srli8.u a0, a0, 1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.srl8.u.i32.i32(i32 %a, i32 1)
  ret i32 %0
}

declare i32 @llvm.riscv.srl8.u.i32.i32(i32, i32)

define i32 @srl16(i32 %a, i32 %b) {
; CHECK-LABEL: srl16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srl16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.srl16.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @srli16(i32 %a, i32 %b) {
; CHECK-LABEL: srli16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srli16 a0, a0, 1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.srl16.i32.i32(i32 %a, i32 1)
  ret i32 %0
}

declare i32 @llvm.riscv.srl16.i32.i32(i32, i32)

define i32 @srl16_u(i32 %a, i32 %b) {
; CHECK-LABEL: srl16_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srl16.u a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.srl16.u.i32.i32(i32 %a, i32 %b)
  ret i32 %0
}

define i32 @srli16_u(i32 %a, i32 %b) {
; CHECK-LABEL: srli16_u:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srli16.u a0, a0, 1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.srl16.u.i32.i32(i32 %a, i32 1)
  ret i32 %0
}

declare i32 @llvm.riscv.srl16.u.i32.i32(i32, i32)

define i32 @stas16(i32 %a, i32 %b) {
; CHECK-LABEL: stas16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    stas16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.stas16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.stas16.i32(i32, i32)

define i32 @stsa16(i32 %a, i32 %b) {
; CHECK-LABEL: stsa16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    stsa16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.stsa16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.stsa16.i32(i32, i32)

define i32 @sub8(i32 %a, i32 %b) {
; CHECK-LABEL: sub8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sub8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sub8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.sub8.i32(i32, i32)

define i32 @sub16(i32 %a, i32 %b) {
; CHECK-LABEL: sub16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sub16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sub16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.sub16.i32(i32, i32)

define i32 @sunpkd810(i32 %a) {
; CHECK-LABEL: sunpkd810:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sunpkd810 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sunpkd810.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.sunpkd810.i32(i32)

define i32 @sunpkd820(i32 %a) {
; CHECK-LABEL: sunpkd820:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sunpkd820 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sunpkd820.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.sunpkd820.i32(i32)

define i32 @sunpkd830(i32 %a) {
; CHECK-LABEL: sunpkd830:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sunpkd830 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sunpkd830.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.sunpkd830.i32(i32)

define i32 @sunpkd831(i32 %a) {
; CHECK-LABEL: sunpkd831:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sunpkd831 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sunpkd831.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.sunpkd831.i32(i32)

define i32 @sunpkd832(i32 %a) {
; CHECK-LABEL: sunpkd832:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sunpkd832 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.sunpkd832.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.sunpkd832.i32(i32)

define i32 @swap8(i32 %a) {
; CHECK-LABEL: swap8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    swap8 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.swap8.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.swap8.i32(i32)

define i32 @swap16(i32 %a) {
; CHECK-LABEL: swap16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    swap16 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.swap16.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.swap16.i32(i32)

define i32 @uclip8(i32 %a) {
; CHECK-LABEL: uclip8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    uclip8 a0, a0, 5
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.uclip8.i32.i32(i32 %a, i32 5)
  ret i32 %0
}

declare i32 @llvm.riscv.uclip8.i32.i32(i32, i32)

define i32 @uclip16(i32 %a) {
; CHECK-LABEL: uclip16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    uclip16 a0, a0, 6
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.uclip16.i32.i32(i32 %a, i32 6)
  ret i32 %0
}

declare i32 @llvm.riscv.uclip16.i32.i32(i32, i32)

define i32 @uclip32(i32 %a) {
; CHECK-LABEL: uclip32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    uclip32 a0, a0, 7
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.uclip32.i32.i32(i32 %a, i32 7)
  ret i32 %0
}

declare i32 @llvm.riscv.uclip32.i32.i32(i32, i32)

define i32 @ucmple8(i32 %a, i32 %b) {
; CHECK-LABEL: ucmple8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ucmple8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ucmple8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ucmple8.i32(i32, i32)

define i32 @ucmple16(i32 %a, i32 %b) {
; CHECK-LABEL: ucmple16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ucmple16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ucmple16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ucmple16.i32(i32, i32)

define i32 @ucmplt8(i32 %a, i32 %b) {
; CHECK-LABEL: ucmplt8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ucmplt8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ucmplt8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ucmplt8.i32(i32, i32)

define i32 @ucmplt16(i32 %a, i32 %b) {
; CHECK-LABEL: ucmplt16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ucmplt16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ucmplt16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ucmplt16.i32(i32, i32)

define i32 @ukadd8(i32 %a, i32 %b) {
; CHECK-LABEL: ukadd8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ukadd8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ukadd8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ukadd8.i32(i32, i32)

define i32 @ukadd16(i32 %a, i32 %b) {
; CHECK-LABEL: ukadd16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ukadd16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ukadd16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ukadd16.i32(i32, i32)

define i32 @ukaddh(i32 %a, i32 %b) {
; CHECK-LABEL: ukaddh:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ukaddh a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ukaddh.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ukaddh.i32(i32, i32)

define i32 @ukaddw(i32 %a, i32 %b) {
; CHECK-LABEL: ukaddw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ukaddw a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ukaddw.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ukaddw.i32(i32, i32)

define i32 @ukcras16(i32 %a, i32 %b) {
; CHECK-LABEL: ukcras16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ukcras16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ukcras16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ukcras16.i32(i32, i32)

define i32 @ukcrsa16(i32 %a, i32 %b) {
; CHECK-LABEL: ukcrsa16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ukcrsa16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ukcrsa16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ukcrsa16.i32(i32, i32)

define i32 @ukstas16(i32 %a, i32 %b) {
; CHECK-LABEL: ukstas16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ukstas16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ukstas16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ukstas16.i32(i32, i32)

define i32 @ukstsa16(i32 %a, i32 %b) {
; CHECK-LABEL: ukstsa16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ukstsa16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ukstsa16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ukstsa16.i32(i32, i32)

define i32 @uksub8(i32 %a, i32 %b) {
; CHECK-LABEL: uksub8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    uksub8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.uksub8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.uksub8.i32(i32, i32)

define i32 @uksub16(i32 %a, i32 %b) {
; CHECK-LABEL: uksub16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    uksub16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.uksub16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.uksub16.i32(i32, i32)

define i32 @uksubh(i32 %a, i32 %b) {
; CHECK-LABEL: uksubh:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    uksubh a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.uksubh.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.uksubh.i32(i32, i32)

define i32 @uksubw(i32 %a, i32 %b) {
; CHECK-LABEL: uksubw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    uksubw a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.uksubw.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.uksubw.i32(i32, i32)

define i32 @umaqa(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: umaqa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    umaqa a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.umaqa.i32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.umaqa.i32.i32(i32, i32, i32)

define i32 @umax8(i32 %a, i32 %b) {
; CHECK-LABEL: umax8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    umax8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.umax8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.umax8.i32(i32, i32)

define i32 @umax16(i32 %a, i32 %b) {
; CHECK-LABEL: umax16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    umax16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.umax16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.umax16.i32(i32, i32)

define i32 @umin8(i32 %a, i32 %b) {
; CHECK-LABEL: umin8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    umin8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.umin8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.umin8.i32(i32, i32)

define i32 @umin16(i32 %a, i32 %b) {
; CHECK-LABEL: umin16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    umin16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.umin16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.umin16.i32(i32, i32)

define i32 @uradd8(i32 %a, i32 %b) {
; CHECK-LABEL: uradd8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    uradd8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.uradd8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.uradd8.i32(i32, i32)

define i32 @uradd16(i32 %a, i32 %b) {
; CHECK-LABEL: uradd16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    uradd16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.uradd16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.uradd16.i32(i32, i32)

define i32 @uraddw(i32 %a, i32 %b) {
; CHECK-LABEL: uraddw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    uraddw a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.uraddw.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.uraddw.i32(i32, i32)

define i32 @urcras16(i32 %a, i32 %b) {
; CHECK-LABEL: urcras16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    urcras16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.urcras16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.urcras16.i32(i32, i32)

define i32 @urcrsa16(i32 %a, i32 %b) {
; CHECK-LABEL: urcrsa16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    urcrsa16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.urcrsa16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.urcrsa16.i32(i32, i32)

define i32 @urstas16(i32 %a, i32 %b) {
; CHECK-LABEL: urstas16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    urstas16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.urstas16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.urstas16.i32(i32, i32)

define i32 @urstsa16(i32 %a, i32 %b) {
; CHECK-LABEL: urstsa16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    urstsa16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.urstsa16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.urstsa16.i32(i32, i32)

define i32 @ursub8(i32 %a, i32 %b) {
; CHECK-LABEL: ursub8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ursub8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ursub8.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ursub8.i32(i32, i32)

define i32 @ursub16(i32 %a, i32 %b) {
; CHECK-LABEL: ursub16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ursub16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ursub16.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ursub16.i32(i32, i32)

define i32 @ursubw(i32 %a, i32 %b) {
; CHECK-LABEL: ursubw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ursubw a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.ursubw.i32(i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.ursubw.i32(i32, i32)

define i32 @zunpkd810(i32 %a) {
; CHECK-LABEL: zunpkd810:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    zunpkd810 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.zunpkd810.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.zunpkd810.i32(i32)

define i32 @zunpkd820(i32 %a) {
; CHECK-LABEL: zunpkd820:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    zunpkd820 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.zunpkd820.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.zunpkd820.i32(i32)

define i32 @zunpkd830(i32 %a) {
; CHECK-LABEL: zunpkd830:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    zunpkd830 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.zunpkd830.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.zunpkd830.i32(i32)

define i32 @zunpkd831(i32 %a) {
; CHECK-LABEL: zunpkd831:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    zunpkd831 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.zunpkd831.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.zunpkd831.i32(i32)

define i32 @zunpkd832(i32 %a) {
; CHECK-LABEL: zunpkd832:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    zunpkd832 a0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.zunpkd832.i32(i32 %a)
  ret i32 %0
}

declare i32 @llvm.riscv.zunpkd832.i32(i32)

define i32 @maddr32(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: maddr32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    maddr32 a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.maddr32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.maddr32.i32(i32, i32, i32)

define i32 @msubr32(i32 %t, i32 %a, i32 %b) {
; CHECK-LABEL: msubr32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    msubr32 a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.msubr32.i32(i32 %t, i32 %a, i32 %b)
  ret i32 %0
}

declare i32 @llvm.riscv.msubr32.i32(i32, i32, i32)

define i32 @rdov() {
; CHECK-LABEL: rdov:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    csrr a0, vxsat
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 @llvm.riscv.rdov.i32()
  ret i32 %0
}

declare i32 @llvm.riscv.rdov.i32()
