; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

define i64 @smul8(i32 signext %a, i32 signext %b) {
; CHECK-LABEL: smul8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smul8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %conv = sext i32 %a to i64
  %conv1 = sext i32 %b to i64
  %0 = tail call i64 @llvm.riscv.smul8.i64.i64(i64 %conv, i64 %conv1)
  ret i64 %0
}

declare i64 @llvm.riscv.smul8.i64.i64(i64, i64)

define i64 @smul16(i32 signext %a, i32 signext %b) {
; CHECK-LABEL: smul16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smul16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %conv = sext i32 %a to i64
  %conv1 = sext i32 %b to i64
  %0 = tail call i64 @llvm.riscv.smul16.i64.i64(i64 %conv, i64 %conv1)
  ret i64 %0
}

declare i64 @llvm.riscv.smul16.i64.i64(i64, i64)

define i64 @smulx8(i32 signext %a, i32 signext %b) {
; CHECK-LABEL: smulx8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smulx8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %conv = sext i32 %a to i64
  %conv1 = sext i32 %b to i64
  %0 = tail call i64 @llvm.riscv.smulx8.i64.i64(i64 %conv, i64 %conv1)
  ret i64 %0
}

declare i64 @llvm.riscv.smulx8.i64.i64(i64, i64)

define i64 @smulx16(i32 signext %a, i32 signext %b) {
; CHECK-LABEL: smulx16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smulx16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %conv = sext i32 %a to i64
  %conv1 = sext i32 %b to i64
  %0 = tail call i64 @llvm.riscv.smulx16.i64.i64(i64 %conv, i64 %conv1)
  ret i64 %0
}

declare i64 @llvm.riscv.smulx16.i64.i64(i64, i64)

define i64 @umul8(i32 signext %a, i32 signext %b) {
; CHECK-LABEL: umul8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    umul8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %conv = sext i32 %a to i64
  %conv1 = sext i32 %b to i64
  %0 = tail call i64 @llvm.riscv.umul8.i64.i64(i64 %conv, i64 %conv1)
  ret i64 %0
}

declare i64 @llvm.riscv.umul8.i64.i64(i64, i64)

define i64 @umul16(i32 signext %a, i32 signext %b) {
; CHECK-LABEL: umul16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    umul16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %conv = sext i32 %a to i64
  %conv1 = sext i32 %b to i64
  %0 = tail call i64 @llvm.riscv.umul16.i64.i64(i64 %conv, i64 %conv1)
  ret i64 %0
}

declare i64 @llvm.riscv.umul16.i64.i64(i64, i64)

define i64 @umulx8(i32 signext %a, i32 signext %b) {
; CHECK-LABEL: umulx8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    umulx8 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %conv = sext i32 %a to i64
  %conv1 = sext i32 %b to i64
  %0 = tail call i64 @llvm.riscv.umulx8.i64.i64(i64 %conv, i64 %conv1)
  ret i64 %0
}

declare i64 @llvm.riscv.umulx8.i64.i64(i64, i64)

define i64 @umulx16(i32 signext %a, i32 signext %b) {
; CHECK-LABEL: umulx16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    umulx16 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %conv = sext i32 %a to i64
  %conv1 = sext i32 %b to i64
  %0 = tail call i64 @llvm.riscv.umulx16.i64.i64(i64 %conv, i64 %conv1)
  ret i64 %0
}

declare i64 @llvm.riscv.umulx16.i64.i64(i64, i64)

define i64 @smal(i64 %a, i32 signext %b) {
; CHECK-LABEL: smal:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smal a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %conv = sext i32 %b to i64
  %0 = tail call i64 @llvm.riscv.smal.i64.i64(i64 %a, i64 %conv)
  ret i64 %0
}

declare i64 @llvm.riscv.smal.i64.i64(i64, i64)

define i64 @radd64(i64 %a, i64 %b) {
; CHECK-LABEL: radd64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    radd64 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.radd64.i64(i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.radd64.i64(i64, i64)

define i64 @uradd64(i64 %a, i64 %b) {
; CHECK-LABEL: uradd64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    uradd64 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.uradd64.i64(i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.uradd64.i64(i64, i64)

define i64 @kadd64(i64 %a, i64 %b) {
; CHECK-LABEL: kadd64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kadd64 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.kadd64.i64(i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.kadd64.i64(i64, i64)

define i64 @ukadd64(i64 %a, i64 %b) {
; CHECK-LABEL: ukadd64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ukadd64 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.ukadd64.i64(i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.ukadd64.i64(i64, i64)

define i64 @rsub64(i64 %a, i64 %b) {
; CHECK-LABEL: rsub64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rsub64 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.rsub64.i64(i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.rsub64.i64(i64, i64)

define i64 @ursub64(i64 %a, i64 %b) {
; CHECK-LABEL: ursub64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ursub64 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.ursub64.i64(i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.ursub64.i64(i64, i64)

define i64 @ksub64(i64 %a, i64 %b) {
; CHECK-LABEL: ksub64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ksub64 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.ksub64.i64(i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.ksub64.i64(i64, i64)

define i64 @uksub64(i64 %a, i64 %b) {
; CHECK-LABEL: uksub64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    uksub64 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.uksub64.i64(i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.uksub64.i64(i64, i64)

define i64 @smar64(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: smar64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smar64 a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.smar64.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.smar64.i64.i64(i64, i64, i64)

define i64 @smsr64(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: smsr64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smsr64 a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.smsr64.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.smsr64.i64.i64(i64, i64, i64)

define i64 @umar64(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: umar64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    umar64 a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.umar64.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.umar64.i64.i64(i64, i64, i64)

define i64 @umsr64(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: umsr64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    umsr64 a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.umsr64.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.umsr64.i64.i64(i64, i64, i64)

define i64 @kmar64(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: kmar64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmada32 a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.kmar64.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.kmar64.i64.i64(i64, i64, i64)

define i64 @kmsr64(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: kmsr64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmsr64 a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.kmsr64.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.kmsr64.i64.i64(i64, i64, i64)

define i64 @ukmar64(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: ukmar64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ukmar64 a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.ukmar64.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.ukmar64.i64.i64(i64, i64, i64)

define i64 @ukmsr64(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: ukmsr64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ukmsr64 a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.ukmsr64.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.ukmsr64.i64.i64(i64, i64, i64)

define i64 @smalbb(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: smalbb:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smalbb a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.smalbb.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.smalbb.i64.i64(i64, i64, i64)

define i64 @smalbt(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: smalbt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smalbt a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.smalbt.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.smalbt.i64.i64(i64, i64, i64)

define i64 @smaltt(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: smaltt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smaltt a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.smaltt.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.smaltt.i64.i64(i64, i64, i64)

define i64 @smalda(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: smalda:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smalda a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.smalda.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.smalda.i64.i64(i64, i64, i64)

define i64 @smalxda(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: smalxda:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smalxda a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.smalxda.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.smalxda.i64.i64(i64, i64, i64)

define i64 @smalds(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: smalds:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smalds a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.smalds.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.smalds.i64.i64(i64, i64, i64)

define i64 @smaldrs(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: smaldrs:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smaldrs a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.smaldrs.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.smaldrs.i64.i64(i64, i64, i64)

define i64 @smalxds(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: smalxds:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smalxds a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.smalxds.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.smalxds.i64.i64(i64, i64, i64)

define i64 @smslda(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: smslda:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smslda a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.smslda.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.smslda.i64.i64(i64, i64, i64)

define i64 @smslxda(i64 %t, i64 %a, i64 %b) {
; CHECK-LABEL: smslxda:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smslxda a0, a1, a2
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.smslxda.i64.i64(i64 %t, i64 %a, i64 %b)
  ret i64 %0
}

declare i64 @llvm.riscv.smslxda.i64.i64(i64, i64, i64)

define i64 @mulr64(i32 signext %a, i32 signext %b) {
; CHECK-LABEL: mulr64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mulr64 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %conv = sext i32 %a to i64
  %conv1 = sext i32 %b to i64
  %0 = tail call i64 @llvm.riscv.mulr64.i64.i64(i64 %conv, i64 %conv1)
  ret i64 %0
}

declare i64 @llvm.riscv.mulr64.i64.i64(i64, i64)

define i64 @mulsr64(i32 signext %a, i32 signext %b) {
; CHECK-LABEL: mulsr64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    smbb32 a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %conv = sext i32 %a to i64
  %conv1 = sext i32 %b to i64
  %0 = tail call i64 @llvm.riscv.mulsr64.i64.i64(i64 %conv, i64 %conv1)
  ret i64 %0
}

declare i64 @llvm.riscv.mulsr64.i64.i64(i64, i64)

define i64 @wext(i64 %a, i64 %b) {
; CHECK-LABEL: wext:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    wext a0, a0, a1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.wext.i64.i64.i64(i64 %a, i64 %b)
  ret i64 %0
}

define i64 @wexti(i64 %a, i64 %b) {
; CHECK-LABEL: wexti:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    wexti a0, a0, 1
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.wext.i64.i64.i64(i64 %a, i64 1)
  ret i64 %0
}

declare i64 @llvm.riscv.wext.i64.i64.i64(i64, i64)
