# NOTE: Assertions have been autogenerated by utils/update_mca_test_checks.py
# RUN: llvm-mca -mtriple=riscv64 -mcpu=xiangshan-nanhu -iterations=300 -show-barriers < %s | FileCheck %s

main:                                   # @main
  addi    sp, sp, -2032
  sd      ra, 2024(sp)                    # 8-byte Folded Spill
  sd      s0, 2016(sp)                    # 8-byte Folded Spill
  addi    s0, sp, 2032
  lui     a0, 39
  addiw   a0, a0, -1744
  sub     sp, sp, a0
  li      a0, 0
  sw      a0, -28(s0)
  lui     a1, 1048537
  addiw   a1, a1, -288
  add     a1, a1, s0
  sw      a0, 0(a1)
  j       .LBB0_1
.LBB0_1:                                # =>This Inner Loop Header: Depth=1
  lui     a0, 1048537
  addiw   a0, a0, -288
  add     a0, a0, s0
  lw      a1, 0(a0)
  lui     a0, 2
  addiw   a0, a0, 1807
  blt     a0, a1, .LBB0_4
  j       .LBB0_2
.LBB0_2:                                #   in Loop: Header=BB0_1 Depth=1
  lui     a0, 1048537
  addiw   a0, a0, -288
  add     a0, a0, s0
  lw      a0, 0(a0)
  slli    a2, a0, 2
  lui     a0, 1048556
  addiw   a0, a0, 1892
  add     a0, a0, s0
  add     a0, a0, a2
  lw      a0, 0(a0)
  lui     a1, 1048547
  addiw   a1, a1, -1244
  add     a1, a1, s0
  add     a1, a1, a2
  lw      a1, 0(a1)
  mulw    a0, a0, a1
  lui     a1, 1048537
  addiw   a1, a1, -284
  add     a1, a1, s0
  add     a1, a1, a2
  lw      a1, 0(a1)
  addw    a0, a0, a1
  lui     a1, 1048566
  addiw   a1, a1, 932
  add     a1, a1, s0
  add     a1, a1, a2
  sw      a0, 0(a1)
  j       .LBB0_3
.LBB0_3:                                #   in Loop: Header=BB0_1 Depth=1
  lui     a0, 1048537
  addiw   a0, a0, -288
  add     a0, a0, s0
  lw      a0, 0(a0)
  addiw   a0, a0, 1
  lui     a1, 1048537
  addiw   a1, a1, -288
  add     a1, a1, s0
  sw      a0, 0(a1)
  j       .LBB0_1
.LBB0_4:
  lw      a0, -28(s0)
  lui     a1, 39
  addiw   a1, a1, -1744
  add     sp, sp, a1
  ld      ra, 2024(sp)                    # 8-byte Folded Reload
  ld      s0, 2016(sp)                    # 8-byte Folded Reload
  addi    sp, sp, 2032
  ret

# CHECK:      Iterations:        300
# CHECK-NEXT: Instructions:      20400
# CHECK-NEXT: Total Cycles:      4058
# CHECK-NEXT: Total uOps:        20400

# CHECK:      Dispatch Width:    6
# CHECK-NEXT: uOps Per Cycle:    5.03
# CHECK-NEXT: IPC:               5.03
# CHECK-NEXT: Block RThroughput: 13.3

# CHECK:      Instruction Info:
# CHECK-NEXT: [1]: #uOps
# CHECK-NEXT: [2]: Latency
# CHECK-NEXT: [3]: RThroughput
# CHECK-NEXT: [4]: MayLoad
# CHECK-NEXT: [5]: MayStore
# CHECK-NEXT: [6]: HasSideEffects (U)
# CHECK-NEXT: [7]: LoadBarrier
# CHECK-NEXT: [8]: StoreBarrier

# CHECK:      [1]    [2]    [3]    [4]    [5]    [6]    [7]    [8]    Instructions:
# CHECK-NEXT:  1      1     0.25                                      addi	sp, sp, -2032
# CHECK-NEXT:  1      1     0.50           *                          sd	ra, 2024(sp)
# CHECK-NEXT:  1      1     0.50           *                          sd	s0, 2016(sp)
# CHECK-NEXT:  1      1     0.25                                      addi	s0, sp, 2032
# CHECK-NEXT:  1      1     0.25                                      lui	a0, 39
# CHECK-NEXT:  1      1     0.25                                      addiw	a0, a0, -1744
# CHECK-NEXT:  1      1     0.25                                      sub	sp, sp, a0
# CHECK-NEXT:  1      1     0.25                                      li	a0, 0
# CHECK-NEXT:  1      1     0.50           *                          sw	a0, -28(s0)
# CHECK-NEXT:  1      1     0.25                                      lui	a1, 1048537
# CHECK-NEXT:  1      1     0.25                                      addiw	a1, a1, -288
# CHECK-NEXT:  1      1     0.25                                      add	a1, a1, s0
# CHECK-NEXT:  1      1     0.50           *                          sw	a0, 0(a1)
# CHECK-NEXT:  1      1     1.00                                      j	.LBB0_1
# CHECK-NEXT:  1      1     0.25                                      lui	a0, 1048537
# CHECK-NEXT:  1      1     0.25                                      addiw	a0, a0, -288
# CHECK-NEXT:  1      1     0.25                                      add	a0, a0, s0
# CHECK-NEXT:  1      3     0.50    *                                 lw	a1, 0(a0)
# CHECK-NEXT:  1      1     0.25                                      lui	a0, 2
# CHECK-NEXT:  1      1     0.25                                      addiw	a0, a0, 1807
# CHECK-NEXT:  1      1     1.00                                      blt	a0, a1, .LBB0_4
# CHECK-NEXT:  1      1     1.00                                      j	.LBB0_2
# CHECK-NEXT:  1      1     0.25                                      lui	a0, 1048537
# CHECK-NEXT:  1      1     0.25                                      addiw	a0, a0, -288
# CHECK-NEXT:  1      1     0.25                                      add	a0, a0, s0
# CHECK-NEXT:  1      3     0.50    *                                 lw	a0, 0(a0)
# CHECK-NEXT:  1      1     0.25                                      slli	a2, a0, 2
# CHECK-NEXT:  1      1     0.25                                      lui	a0, 1048556
# CHECK-NEXT:  1      1     0.25                                      addiw	a0, a0, 1892
# CHECK-NEXT:  1      1     0.25                                      add	a0, a0, s0
# CHECK-NEXT:  1      1     0.25                                      add	a0, a0, a2
# CHECK-NEXT:  1      3     0.50    *                                 lw	a0, 0(a0)
# CHECK-NEXT:  1      1     0.25                                      lui	a1, 1048547
# CHECK-NEXT:  1      1     0.25                                      addiw	a1, a1, -1244
# CHECK-NEXT:  1      1     0.25                                      add	a1, a1, s0
# CHECK-NEXT:  1      1     0.25                                      add	a1, a1, a2
# CHECK-NEXT:  1      3     0.50    *                                 lw	a1, 0(a1)
# CHECK-NEXT:  1      3     0.50                                      mulw	a0, a0, a1
# CHECK-NEXT:  1      1     0.25                                      lui	a1, 1048537
# CHECK-NEXT:  1      1     0.25                                      addiw	a1, a1, -284
# CHECK-NEXT:  1      1     0.25                                      add	a1, a1, s0
# CHECK-NEXT:  1      1     0.25                                      add	a1, a1, a2
# CHECK-NEXT:  1      3     0.50    *                                 lw	a1, 0(a1)
# CHECK-NEXT:  1      1     0.25                                      addw	a0, a0, a1
# CHECK-NEXT:  1      1     0.25                                      lui	a1, 1048566
# CHECK-NEXT:  1      1     0.25                                      addiw	a1, a1, 932
# CHECK-NEXT:  1      1     0.25                                      add	a1, a1, s0
# CHECK-NEXT:  1      1     0.25                                      add	a1, a1, a2
# CHECK-NEXT:  1      1     0.50           *                          sw	a0, 0(a1)
# CHECK-NEXT:  1      1     1.00                                      j	.LBB0_3
# CHECK-NEXT:  1      1     0.25                                      lui	a0, 1048537
# CHECK-NEXT:  1      1     0.25                                      addiw	a0, a0, -288
# CHECK-NEXT:  1      1     0.25                                      add	a0, a0, s0
# CHECK-NEXT:  1      3     0.50    *                                 lw	a0, 0(a0)
# CHECK-NEXT:  1      1     0.25                                      addiw	a0, a0, 1
# CHECK-NEXT:  1      1     0.25                                      lui	a1, 1048537
# CHECK-NEXT:  1      1     0.25                                      addiw	a1, a1, -288
# CHECK-NEXT:  1      1     0.25                                      add	a1, a1, s0
# CHECK-NEXT:  1      1     0.50           *                          sw	a0, 0(a1)
# CHECK-NEXT:  1      1     1.00                                      j	.LBB0_1
# CHECK-NEXT:  1      3     0.50    *                                 lw	a0, -28(s0)
# CHECK-NEXT:  1      1     0.25                                      lui	a1, 39
# CHECK-NEXT:  1      1     0.25                                      addiw	a1, a1, -1744
# CHECK-NEXT:  1      1     0.25                                      add	sp, sp, a1
# CHECK-NEXT:  1      3     0.50    *                                 ld	ra, 2024(sp)
# CHECK-NEXT:  1      3     0.50    *                                 ld	s0, 2016(sp)
# CHECK-NEXT:  1      1     0.25                                      addi	sp, sp, 2032
# CHECK-NEXT:  1      1     1.00                                      ret

# CHECK:      Resources:
# CHECK-NEXT: [0.0] - NanHuFloatArith
# CHECK-NEXT: [0.1] - NanHuFloatArith
# CHECK-NEXT: [0.2] - NanHuFloatArith
# CHECK-NEXT: [0.3] - NanHuFloatArith
# CHECK-NEXT: [1.0] - NanHuFloatMisc
# CHECK-NEXT: [1.1] - NanHuFloatMisc
# CHECK-NEXT: [2.0] - NanHuFloatPipe
# CHECK-NEXT: [2.1] - NanHuFloatPipe
# CHECK-NEXT: [2.2] - NanHuFloatPipe
# CHECK-NEXT: [2.3] - NanHuFloatPipe
# CHECK-NEXT: [3.0] - NanHuIntArith
# CHECK-NEXT: [3.1] - NanHuIntArith
# CHECK-NEXT: [3.2] - NanHuIntArith
# CHECK-NEXT: [3.3] - NanHuIntArith
# CHECK-NEXT: [4]   - NanHuIntMisc
# CHECK-NEXT: [5.0] - NanHuIntMulDiv
# CHECK-NEXT: [5.1] - NanHuIntMulDiv
# CHECK-NEXT: [6.0] - NanHuIntPipe
# CHECK-NEXT: [6.1] - NanHuIntPipe
# CHECK-NEXT: [6.2] - NanHuIntPipe
# CHECK-NEXT: [6.3] - NanHuIntPipe
# CHECK-NEXT: [7.0] - NanHuMemLoad
# CHECK-NEXT: [7.1] - NanHuMemLoad
# CHECK-NEXT: [8.0] - NanHuMemPipe
# CHECK-NEXT: [8.1] - NanHuMemPipe
# CHECK-NEXT: [8.2] - NanHuMemPipe
# CHECK-NEXT: [8.3] - NanHuMemPipe
# CHECK-NEXT: [9.0] - NanHuMemSave
# CHECK-NEXT: [9.1] - NanHuMemSave

# CHECK:      Resource pressure per iteration:
# CHECK-NEXT: [0.0]  [0.1]  [0.2]  [0.3]  [1.0]  [1.1]  [2.0]  [2.1]  [2.2]  [2.3]  [3.0]  [3.1]  [3.2]  [3.3]  [4]    [5.0]  [5.1]  [6.0]  [6.1]  [6.2]  [6.3]  [7.0]  [7.1]  [8.0]  [8.1]  [8.2]  [8.3]  [9.0]  [9.1]
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     11.50  11.50  11.50  11.50  6.00   0.50   0.50   13.25  13.25  13.25  13.25  4.50   4.50   3.75   3.75   3.75   3.75   3.00   3.00

# CHECK:      Resource pressure by instruction:
# CHECK-NEXT: [0.0]  [0.1]  [0.2]  [0.3]  [1.0]  [1.1]  [2.0]  [2.1]  [2.2]  [2.3]  [3.0]  [3.1]  [3.2]  [3.3]  [4]    [5.0]  [5.1]  [6.0]  [6.1]  [6.2]  [6.3]  [7.0]  [7.1]  [8.0]  [8.1]  [8.2]  [8.3]  [9.0]  [9.1]  Instructions:
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -     0.50   0.50    -      -      -     0.49    -     0.50   0.01    -      -      -      -      -      -      -      -     addi	sp, sp, -2032
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     0.50    -     0.49   0.01    -     1.00   sd	ra, 2024(sp)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     0.49   0.01   0.50   1.00    -     sd	s0, 2016(sp)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.50    -      -     0.50    -      -      -      -     0.50    -     0.50    -      -      -      -      -      -      -      -     addi	s0, sp, 2032
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.50   0.01   0.49    -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     lui	a0, 39
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.99    -      -      -      -      -      -     0.25   0.25   0.26   0.25    -      -      -      -      -      -      -      -     addiw	a0, a0, -1744
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.01   0.50   0.50    -      -      -     0.49    -     0.50    -      -      -      -      -      -      -      -      -     sub	sp, sp, a0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.50   0.01   0.49    -      -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     li	a0, 0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -      -     1.00   sw	a0, -28(s0)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -     0.01   0.99    -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     lui	a1, 1048537
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.01   0.49    -     0.50    -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     addiw	a1, a1, -288
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.50   0.01   0.49    -      -      -     0.25   0.26   0.25   0.25    -      -      -      -      -      -      -      -     add	a1, a1, s0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     0.50    -     0.50   1.00    -     sw	a0, 0(a1)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -     1.00    -      -     0.50    -     0.49    -      -      -      -      -      -      -      -      -     j	.LBB0_1
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.49   0.50    -      -      -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     lui	a0, 1048537
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.50   0.50    -      -      -      -      -     0.50    -     0.49    -      -      -      -      -      -      -      -     addiw	a0, a0, -288
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.50    -     0.49    -      -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     add	a0, a0, s0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     0.50   0.50   0.25   0.25   0.25   0.25    -      -     lw	a1, 0(a0)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.99    -      -      -      -      -      -     0.50    -     0.49    -      -      -      -      -      -      -      -      -     lui	a0, 2
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.99    -      -      -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     addiw	a0, a0, 1807
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -     1.00    -      -      -     0.49    -     0.51    -      -      -      -      -      -      -      -     blt	a0, a1, .LBB0_4
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -     1.00    -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     j	.LBB0_2
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.01   0.50   0.50    -      -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     lui	a0, 1048537
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     addiw	a0, a0, -288
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.01   0.99    -      -      -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     add	a0, a0, s0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     0.50   0.50   0.25   0.25   0.25   0.25    -      -     lw	a0, 0(a0)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.49   0.01   0.50    -      -      -     0.25   0.25   0.25   0.26    -      -      -      -      -      -      -      -     slli	a2, a0, 2
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     1.00    -      -      -      -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     lui	a0, 1048556
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.49    -     0.50    -      -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     addiw	a0, a0, 1892
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -      -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     add	a0, a0, s0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -      -      -      -      -     0.49    -     0.51    -      -      -      -      -      -      -      -     add	a0, a0, a2
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     1.00    -     0.50    -     0.50    -      -     lw	a0, 0(a0)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.01    -     0.99    -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     lui	a1, 1048547
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     addiw	a1, a1, -1244
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.01   0.50    -     0.50    -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     add	a1, a1, s0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -      -      -     0.49    -     0.51    -      -      -      -      -      -      -      -      -     add	a1, a1, a2
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     1.00    -     0.50    -     0.50    -      -      -     lw	a1, 0(a1)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     0.50   0.50    -     0.49    -     0.50    -      -      -      -      -      -      -      -     mulw	a0, a0, a1
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.50   0.01   0.49    -      -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     lui	a1, 1048537
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -      -      -      -     0.25   0.26   0.25   0.25    -      -      -      -      -      -      -      -     addiw	a1, a1, -284
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -     0.99    -      -      -      -     0.49    -     0.51    -      -      -      -      -      -      -      -      -     add	a1, a1, s0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -      -      -      -      -     0.51    -     0.49    -      -      -      -      -      -      -      -     add	a1, a1, a2
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     1.00    -     0.50    -     0.50    -      -     lw	a1, 0(a1)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -      -      -      -      -     0.50    -     0.50    -      -      -      -      -      -      -      -     addw	a0, a0, a1
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -      -      -     0.50    -     0.49    -      -      -      -      -      -      -      -      -     lui	a1, 1048566
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.01    -      -     0.99    -      -      -     0.50   0.01   0.50    -      -      -      -      -      -      -      -      -     addiw	a1, a1, 932
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.49   0.50    -      -      -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     add	a1, a1, s0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -      -      -     0.51    -     0.49    -      -      -      -      -      -      -      -      -     add	a1, a1, a2
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -     1.00   sw	a0, 0(a1)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -     1.00    -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     j	.LBB0_3
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.99    -      -     0.01    -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     lui	a0, 1048537
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.01   0.99    -      -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     addiw	a0, a0, -288
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.50    -      -     0.50    -      -      -      -     0.49   0.01   0.50    -      -      -      -      -      -      -      -     add	a0, a0, s0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     1.00    -     0.50    -     0.50    -      -      -     lw	a0, 0(a0)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.01   0.49   0.50    -      -      -      -     0.49    -     0.50    -      -      -      -      -      -      -      -     addiw	a0, a0, 1
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.99    -      -      -      -      -     0.26   0.25   0.25   0.25    -      -      -      -      -      -      -      -     lui	a1, 1048537
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -     0.49   0.50    -      -      -     0.49   0.01   0.50    -      -      -      -      -      -      -      -      -     addiw	a1, a1, -288
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.50   0.50    -      -      -      -      -      -     0.50    -     0.50    -      -      -      -      -      -      -      -     add	a1, a1, s0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -     1.00    -     sw	a0, 0(a1)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -     1.00    -      -     0.01   0.50    -     0.49    -      -      -      -      -      -      -      -     j	.LBB0_1
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     0.50   0.50   0.25   0.25   0.25   0.25    -      -     lw	a0, -28(s0)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -     0.50   0.50    -      -      -     0.50    -     0.50    -      -      -      -      -      -      -      -      -     lui	a1, 39
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.50    -     0.50    -      -      -      -     0.25   0.25   0.25   0.26    -      -      -      -      -      -      -      -     addiw	a1, a1, -1744
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -     0.99    -     0.01    -      -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     add	sp, sp, a1
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     0.50   0.50   0.25   0.25   0.25   0.25    -      -     ld	ra, 2024(sp)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     0.50   0.50   0.25   0.25   0.25   0.25    -      -     ld	s0, 2016(sp)
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -     0.99    -      -      -      -     0.25   0.25   0.26   0.25    -      -      -      -      -      -      -      -     addi	sp, sp, 2032
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -     1.00    -      -     0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -     ret
