// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-k -emit-llvm %s -o - \
// RUN:     | FileCheck %s  -check-prefix=RV64ZKN

#include <rvkintrin.h>
int64_t test_rv64_aes64dsm(int64_t rs1, int64_t rs2){
    return _rv64_aes64dsm(rs1,rs2);
}
