; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32  --mattr=+zce-beqi,+zce-bnei -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32I %s

define i64 @cmovcc64(i32 %a, i64 %b, i64 %c) nounwind {
; RV32I-LABEL: cmovcc64:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    bnei a0, 12, .LBB0_2
; RV32I-NEXT:  # %bb.1: # %entry
; RV32I-NEXT:    mv a3, a1
; RV32I-NEXT:    mv a4, a2
; RV32I-NEXT:  .LBB0_2: # %entry
; RV32I-NEXT:    mv a0, a3
; RV32I-NEXT:    mv a1, a4
; RV32I-NEXT:    ret
entry:
  %new = zext i32 %a to i64
  %cmp = icmp ne i64 12, %new
  %cond = select i1 %cmp, i64 %c, i64 %b
  ret i64 %cond
}
