// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -O2 -target-feature +experimental-p \
// RUN:   -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-RV32 %s
// CHECK-RV32-LABEL: @clrov(
// CHECK-RV32-NEXT:  entry:
// CHECK-RV32-NEXT:    tail call void @llvm.riscv.clrov()
// CHECK-RV32-NEXT:    unreachable
//
void clrov(){
  __rv_clrov();
}
