; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-v -O0 \
; RUN:    < %s | FileCheck --check-prefix=SPILL-O0 %s

define <vscale x 2 x i64> @spill_lmul_2(<vscale x 2 x i64> %va) nounwind {
; SPILL-O0-LABEL: spill_lmul_2:
; SPILL-O0:       # %bb.0: # %entry
; SPILL-O0-NEXT:	addi	sp, sp, -32
; SPILL-O0-NEXT:	sd	ra, 24(sp)
; SPILL-O0-NEXT:	sd	s0, 16(sp)
; SPILL-O0-NEXT:	addi	s0, sp, 32
; SPILL-O0-NEXT:	csrr	a0, vlenb
; SPILL-O0-NEXT:	slli	a0, a0, 1
; SPILL-O0-NEXT:	sub	sp, sp, a0
; SPILL-O0-NEXT:	sd	sp, -24(s0)
; SPILL-O0-NEXT:	ld	a0, -24(s0)
; SPILL-O0-NEXT:	vs2r.v	v16, (a0)
; SPILL-O0-NEXT:	#APP
; SPILL-O0-NEXT:	#NO_APP
; SPILL-O0-NEXT:	ld	a0, -24(s0)
; SPILL-O0-NEXT:	vl2re8.v	v16, (a0)
; SPILL-O0-NEXT:	addi	sp, s0, -32
; SPILL-O0-NEXT:	ld	s0, 16(sp)
; SPILL-O0-NEXT:	ld	ra, 24(sp)
; SPILL-O0-NEXT:	addi	sp, sp, 32
; SPILL-O0-NEXT:	ret
entry:
  call void asm sideeffect "",
  "~{v0},~{v1},~{v2},~{v3},~{v4},~{v5},~{v6},~{v7},~{v8},~{v9},~{v10},~{v11},~{v12},~{v13},~{v14},~{v15},~{v16},~{v17},~{v18},~{v19},~{v20},~{v21},~{v22},~{v23},~{v24},~{v25},~{v26},~{v27},~{v28},~{v29},~{v30},~{v31}"()

  ret <vscale x 2 x i64> %va
}